package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsSign;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DtsSignMapper {

    DtsSign signInToDay(@Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    int insert(DtsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    int insertSelective(DtsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsSign selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsSign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    DtsSign selectByPrimaryKey(Integer id);

    /**
     * selectByUserId
     * @param userId userId
     * @return List<DtsSign>
     */
    List<DtsSign> selectByUserId(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsSign record);
}